version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: ecom_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecom_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecom_network

  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ecom_network
    depends_on:
      - postgres

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: ecom_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ecom_network
    depends_on:
      - app

  # Redis (Optional - for caching)
  redis:
    image: redis:alpine
    container_name: ecom_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ecom_network

volumes:
  postgres_data:
    driver: local

networks:
  ecom_network:
    driver: bridge
